# Generated by Django 2.2.6 on 2019-12-24 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_drink_drinksession_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='effects',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='time_consumed',
        ),
        migrations.RemoveField(
            model_name='drinksession',
            name='drinks',
        ),
        migrations.CreateModel(
            name='DrinkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_consumed', models.DateTimeField()),
                ('effects', models.CharField(max_length=300)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Drink')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.DrinkSession')),
            ],
        ),
    ]
