# Generated by Django 3.0 on 2019-12-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191224_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinksession',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='drinktime',
            name='time_consumed',
            field=models.TimeField(),
        ),
    ]
