# Generated by Django 3.0 on 2020-01-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191229_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinktime',
            options={'ordering': ['time_consumed']},
        ),
    ]
